### PR TITLE
Fix #68: Support negative value in enums

### LINKED ISSUE #68: Parse error: Negative value in enums
https://github.com/Microsoft/vscode/blob/bc7b804fdec62173b5437d188e6aa64c036d24f0/src/vs/vscode.d.ts#L3796

number expected

```typescript
export enum ViewColumn {
  Active = -1
}
```

### PR DESCRIPTION
**Pull request by exoego**
This PR fixes #68.

I could not find any TypeScript official docs to explain negative value in enums, but obviously it is supported, since there are lots of occurence in the wild.

```bash
$ git clone https://github.com/DefinitelyTyped/DefinitelyTyped
$ cd https://github.com/DefinitelyTyped/DefinitelyTyped
$ git grep -E "\w+ = -[0-9]+" | wc -l
1247
```

The issue https://github.com/Microsoft/TypeScript/issues/150 might explains TypeScript allows negative value in enums.

### CODE REVIEW

File: src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala [hunk 1]
```diff
@@ -104,7 +104,7 @@ class TSDefParser extends StdTokenParsers with ImplicitConversions {
     "enum" ~> typeName ~ ("{" ~> ambientEnumBody <~ "}") ^^ EnumDecl
 
   lazy val ambientEnumBody: Parser[List[Ident]] =
-    repsep(identifier <~ opt("=" ~ (numericLit | stringLit) ), ",") <~ opt(",")
+    repsep(identifier <~ opt("=" ~ ((opt("-") ~> numericLit) | stringLit) ), ",") <~ opt(",")
```
Comment (sjrd) [inline src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala]: Why is this change necessary, given that there is also a change at the source, in `numericLiteral`?

Comment (exoego) [reply src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala]: Oops. This was accidentally commited and is not required.
I remove this.
