### PR TITLE
Fix #69: Support readonly indexable types

### LINKED ISSUE #69: Parse error: Modifier + Indexable Types
Parse error at 3601.12
number expected
```typescript
                readonly [key: string]: any;
                         ^
```

https://github.com/Microsoft/vscode/blob/bc7b804fdec62173b5437d188e6aa64c036d24f0/src/vs/vscode.d.ts#L3601

### PR DESCRIPTION
**Pull request by exoego**
This PR fixes #69.

scala-js-ts-importer can convert indexable types, which has index access a.k.a. bracket access.
TypeScript allows indexable types to have `readonly` modifier, so that the types can prevent assignment to their indices.

This PR adds support of readonly indexable types.

```TypeScript
interface A {
    [key: string]: string;
}
interface B {
    readonly [key: string]: string;
}
```

```Scala
@js.native
trait A extends js.Object {
  @JSBracketAccess
  def apply(index: String): String = js.native
  @JSBracketAccess
  def update(index: String, v: String): Unit = js.native
}

@js.native
trait B extends js.Object {
  @JSBracketAccess
  def apply(index: String): String = js.native
}
```

# Affect of this
5 occurences of readonly indexable types are found in DefinitelyTyped, as of 2018-03-23.

```bash
$ git clone https://github.com/DefinitelyTyped/DefinitelyTyped
$ cd https://github.com/DefinitelyTyped/DefinitelyTyped
$ git grep -E "readonly\s*\[\w+: \w+\]"
types/eslint-visitor-keys/index.d.ts:    readonly [type: string]: ReadonlyArray<string> | undefined;
types/lowdb/index.d.ts:  readonly [n: number]: T;
types/maxmind/index.d.ts:    readonly [index: string]: string;
types/react-tagsinput/index.d.ts:      readonly [prop: string]: any;
types/react-tagsinput/index.d.ts:        readonly [prop: string]: any;
```

### CODE REVIEW

File: samples/indexabletypes.d.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// extract example from https://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types
+interface NumberDictionary {
+    [index: string]: number;
+}
+interface ReadonlyStringArray {
+    [index: number]: string;
```
Comment (sjrd) [inline samples/indexabletypes.d.ts]: `ReadonlyStringArray` should have the `readonly` modifier. (the example you cite has it, and it makes sense)

File: samples/indexabletypes.d.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+}
+
+// extract example from https://github.com/Microsoft/vscode/blob/bc7b804fdec62173b5437d188e6aa64c036d24f0/src/vs/vscode.d.ts#L3601
+export interface WorkspaceConfiguration {
+    readonly [key: string]: any;
+}
```
Comment (sjrd) [inline samples/indexabletypes.d.ts]: Please an EOL at the end of the file, so that git and GitHub don't display that no-EOL mark.

File: samples/indexabletypes.d.ts.scala [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+  @JSBracketAccess
+  def update(index: String, v: Double): Unit = js.native
+}
+
+@js.native
+trait ReadonlyStringArray extends js.Object {
+  @JSBracketAccess
+  def apply(index: Double): String = js.native
+  @JSBracketAccess
+  def update(index: Double, v: String): Unit = js.native
```
Comment (sjrd) [inline samples/indexabletypes.d.ts.scala]: This test should be adapted after adding `readonly` in `ReadonlyStringArray`, obviously.

File: src/main/scala/org/scalajs/tools/tsimporter/Trees.scala [hunk 4]
```diff
@@ -181,7 +181,7 @@ object Trees {
 
   case class ConstructorMember(signature: FunSignature) extends MemberTree
 
-  case class IndexMember(indexName: Ident, indexType: TypeTree, valueType: TypeTree) extends MemberTree
+  case class IndexMember(indexName: Ident, indexType: TypeTree, valueType: TypeTree, readonly: Boolean) extends MemberTree
```
Comment (sjrd) [inline src/main/scala/org/scalajs/tools/tsimporter/Trees.scala]: I would prefer to use a `modifiers: Modifiers`, like for the other members.

Comment (exoego) [reply src/main/scala/org/scalajs/tools/tsimporter/Trees.scala]: I agress for future expansion (`private`, `static` or something)

File: samples/indexabletypes.d.ts (hunk 1 above)
Comment (exoego) [reply samples/indexabletypes.d.ts]: Oops.
Test has been cleaned up, including EOL at the end of file.
